### ISSUE TITLE
Resolved Issue with 403 Response by Adding User Agent

### ISSUE THREAD

**Issue by mohammadx0098** [moeinerfanian/writeup-finder#1]
Thank you for the great program you wrote. It really helped me a lot. ❤️ 
However, after a while, I noticed that although the request is being sent, I'm getting a 403 response from the medium website. I tried adding a user agent, and with that modification, the issue was resolved.

```
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'}
    response = requests.get(url, headers = headers)
```

**Comment by electro0nes** [comment]
Thank you very much, I will definitely use your code
